name: Auto approve

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:

  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Auto Approve') }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules:  'false'
          fetch-depth: 0
        
      - name: Check for changed files that are probably public API
        id: protected-files-changes
        uses: tj-actions/changed-files@v35
        with:
          files: |
            app/app_pb/**
            contrib/**/include/**
            contrib/ecaltime/ecaltime_pb/**
            ecal/core/cfg/**
            ecal/core/include/**
            ecal/core_pb/**
            ecal/pb/**
            lang/**
            thirdparty/**
            .gitmodules
            
      - name: Public API has changed?
        if: steps.protected-files-changes.outputs.any_changed == 'true'
        run: |
          echo "ERROR: Protected files have been changed:"
          echo "${{ steps.protected-files-changes.outputs.all_changed_files }}"
          exit 1
            
      - uses: hmarr/auto-approve-action@v3
        if: steps.protected-files-changes.outputs.any_changed == 'false'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
